### ISSUE TITLE
[feature request] - preference to change or disable keyboard shortcuts

### ISSUE THREAD

**Issue by Bub-la-bub** [zddhub/PixelsMeasure#2]
PixelsMeasure is a good app, but it would be nice if the user had the ability to customize or remove the keyboard commands it uses to activate.  PixelsMeasure automatically uses shift-cmd-G to trigger measurements disabling other apps from using that keyboard shortcut but that command is used by the Finder as "Go to folder..." and within many other programs as "Find previous" and losing those keyboard commands in those apps can be very frustrating.

Most other utilities with similar features allow for customizing their keyboard shortcuts or disabling them completely, which allow the user to keep any existing commands and I think this would be a nice addition to the app.

**Comment by zddhub** [comment]
Hi @Bub-la-bub , thanks for your feedback.

We had added customize keyboard shortcuts feature since [version 1.7.2 or later](https://apps.apple.com/cn/app/pixelsmeasure/id1638740542?l=en&mt=12). You can set it to different combo or remove it. Enjoy it.

Please let me know if you have any question
